// The lesson curriculum now lives in lib/lessons.js (documentation-style,
// beginner -> advanced). Re-exported here so existing imports keep working.
export { lessons, TRACKS, getLesson } from './lessons';

export const algorithms=[
{id:'bell',title:'Bell State',level:'Beginner',desc:'The shortest path from a single-qubit superposition to entanglement.',why:'Experience entanglement rather than only reading about it.',steps:['Prepare |00⟩','Apply H to q0','Apply CNOT q0→q1','Measure both qubits'],circuit:[{name:'H',qubit:0,col:0},{name:'CNOT',qubit:0,target:1,col:1},{name:'M',qubit:0,col:2},{name:'M',qubit:1,col:2}]},
{id:'deutsch-jozsa',title:'Deutsch–Jozsa',level:'Intermediate',desc:'Explore how interference can distinguish promised function classes.',why:'Build intuition for oracle queries and interference.',steps:['Prepare input register','Create superposition','Query oracle','Interfere and measure'],circuit:[{name:'H',qubit:0,col:0},{name:'H',qubit:1,col:0},{name:'H',qubit:0,col:2},{name:'H',qubit:1,col:2}]},
{id:'grover',title:'Grover Search',level:'Intermediate',desc:'Visualize amplitude amplification as probability moves toward a marked state.',why:'See quantum speedup as a geometric probability transformation.',steps:['Initialize superposition','Mark target','Apply diffusion','Measure'],circuit:[{name:'H',qubit:0,col:0},{name:'H',qubit:1,col:0},{name:'X',qubit:0,col:1},{name:'H',qubit:0,col:2},{name:'H',qubit:1,col:2}]},
{id:'teleportation',title:'Quantum Teleportation',level:'Advanced',desc:'Transfer an unknown qubit state using entanglement and two classical bits.',why:'Connect entanglement, measurement and conditional operations.',steps:['Create Bell pair','Entangle source','Measure source pair','Apply corrections'],circuit:[{name:'H',qubit:1,col:0},{name:'CNOT',qubit:1,target:2,col:1},{name:'CNOT',qubit:0,target:1,col:2},{name:'H',qubit:0,col:3}]},
{id:'superdense',title:'Superdense Coding',level:'Advanced',desc:'Send two classical bits using one qubit plus shared entanglement.',why:'See how entanglement changes the communication resource.',steps:['Create Bell pair','Encode two bits','Decode with inverse Bell circuit','Measure'],circuit:[{name:'H',qubit:0,col:0},{name:'CNOT',qubit:0,target:1,col:1},{name:'X',qubit:0,col:2},{name:'CNOT',qubit:0,target:1,col:3},{name:'H',qubit:0,col:4}]}
];
export const challenges=[
{id:'x-gate',title:'Flip the qubit',difficulty:'Easy',xp:40,goal:'Create |1⟩ from the initial |0⟩ state using one gate.',hint:'Which gate maps |0⟩ to |1⟩?',validate:c=>c.some(g=>g.name==='X'&&g.qubit===0)},
{id:'balanced',title:'Make 50/50',difficulty:'Easy',xp:50,goal:'Create a balanced measurement distribution from |0⟩.',hint:'Try the Hadamard gate.',validate:c=>c.some(g=>g.name==='H'&&g.qubit===0)},
{id:'undo-h',title:'Undo superposition',difficulty:'Medium',xp:70,goal:'Use two gates so the final state returns to |0⟩.',hint:'Hadamard is its own inverse: H² = I.',validate:c=>c.filter(g=>g.name==='H'&&g.qubit===0).length>=2},
{id:'bell',title:'Create entanglement',difficulty:'Medium',xp:100,goal:'Build a Bell state with correlated 00 and 11 outcomes.',hint:'Start with H(q0), then connect q0 to q1 using CNOT.',validate:c=>c.some(g=>g.name==='H'&&g.qubit===0)&&c.some(g=>g.name==='CNOT'&&g.qubit===0&&g.target===1)},
{id:'grover',title:'Amplify a target',difficulty:'Hard',xp:150,goal:'Use a two-qubit circuit containing a diffusion-style sequence to explore amplitude amplification.',hint:'Start with H on both qubits; experiment with X and H around the target.',validate:c=>c.filter(g=>g.name==='H').length>=2&&c.some(g=>g.name==='X')}
];
