export const lessons=[
{id:'qubits',title:'Qubits & Quantum States',level:'Foundation',time:'12 min',tag:'01',desc:'Understand |0⟩, |1⟩ and superposition as probability amplitudes.',formula:'|ψ⟩ = α|0⟩ + β|1⟩',experiment:'Set α and β, then predict what a computational-basis measurement will reveal.'},
{id:'superposition',title:'Superposition',level:'Foundation',time:'10 min',tag:'02',desc:'See how the Hadamard gate creates a balanced superposition from |0⟩.',formula:'H|0⟩ = (|0⟩ + |1⟩)/√2',experiment:'Run 1,000 shots after H and compare the observed distribution with 50/50.'},
{id:'gates',title:'Quantum Gates',level:'Core',time:'16 min',tag:'03',desc:'Treat gates as unitary transformations acting on quantum states.',formula:'|ψ′⟩ = U|ψ⟩',experiment:'Try X, Z and H, then use H twice to verify that H² = I.'},
{id:'measurement',title:'Measurement',level:'Core',time:'14 min',tag:'04',desc:'Connect amplitudes to probabilities and understand collapse through repeated shots.',formula:'P(x)=|⟨x|ψ⟩|²',experiment:'Predict a distribution before running the circuit, then compare prediction vs reality.'},
{id:'entanglement',title:'Entanglement',level:'Intermediate',time:'18 min',tag:'05',desc:'Create a Bell state and explore correlations that cannot be described as independent qubits.',formula:'|Φ⁺⟩=(|00⟩+|11⟩)/√2',experiment:'Build H(q0) → CNOT(q0,q1) and observe only 00/11 outcomes.'},
{id:'circuits',title:'Quantum Circuits',level:'Intermediate',time:'20 min',tag:'06',desc:'Compose gates, controlled operations, measurement and circuit depth into executable algorithms.',formula:'U = Uₙ…U₂U₁',experiment:'Build a circuit, animate it step-by-step and explain each transformation.'}
];
export const algorithms=[
{id:'bell',title:'Bell State',level:'Beginner',desc:'The shortest path from a single-qubit superposition to entanglement.',why:'Experience entanglement rather than only reading about it.',steps:['Prepare |00⟩','Apply H to q0','Apply CNOT q0→q1','Measure both qubits'],circuit:[{name:'H',qubit:0,col:0},{name:'CNOT',qubit:0,target:1,col:1},{name:'M',qubit:0,col:2},{name:'M',qubit:1,col:2}]},
{id:'deutsch-jozsa',title:'Deutsch–Jozsa',level:'Intermediate',desc:'Explore how interference can distinguish promised function classes.',why:'Build intuition for oracle queries and interference.',steps:['Prepare input register','Create superposition','Query oracle','Interfere and measure'],circuit:[{name:'H',qubit:0,col:0},{name:'H',qubit:1,col:0},{name:'H',qubit:0,col:2},{name:'H',qubit:1,col:2}]},
{id:'grover',title:'Grover Search',level:'Intermediate',desc:'Visualize amplitude amplification as probability moves toward a marked state.',why:'See quantum speedup as a geometric probability transformation.',steps:['Initialize superposition','Mark target','Apply diffusion','Measure'],circuit:[{name:'H',qubit:0,col:0},{name:'H',qubit:1,col:0},{name:'X',qubit:0,col:1},{name:'H',qubit:0,col:2},{name:'H',qubit:1,col:2}]},
{id:'teleportation',title:'Quantum Teleportation',level:'Advanced',desc:'Transfer an unknown qubit state using entanglement and two classical bits.',why:'Connect entanglement, measurement and conditional operations.',steps:['Create Bell pair','Entangle source','Measure source pair','Apply corrections'],circuit:[{name:'H',qubit:1,col:0},{name:'CNOT',qubit:1,target:2,col:1},{name:'CNOT',qubit:0,target:1,col:2},{name:'H',qubit:0,col:3}]},
{id:'superdense',title:'Superdense Coding',level:'Advanced',desc:'Send two classical bits using one qubit plus shared entanglement.',why:'See how entanglement changes the communication resource.',steps:['Create Bell pair','Encode two bits','Decode with inverse Bell circuit','Measure'],circuit:[{name:'H',qubit:0,col:0},{name:'CNOT',qubit:0,target:1,col:1},{name:'X',qubit:0,col:2},{name:'CNOT',qubit:0,target:1,col:3},{name:'H',qubit:0,col:4}]}
];
export const challenges=[
{id:'x-gate',title:'Flip the qubit',difficulty:'Easy',xp:40,goal:'Create |1⟩ from the initial |0⟩ state using one gate.',hint:'Which gate maps |0⟩ to |1⟩?',validate:c=>c.some(g=>g.name==='X'&&g.qubit===0)},
{id:'balanced',title:'Make 50/50',difficulty:'Easy',xp:50,goal:'Create a balanced measurement distribution from |0⟩.',hint:'Try the Hadamard gate.',validate:c=>c.some(g=>g.name==='H'&&g.qubit===0)},
{id:'undo-h',title:'Undo superposition',difficulty:'Medium',xp:70,goal:'Use two gates so the final state returns to |0⟩.',hint:'Hadamard is its own inverse: H² = I.',validate:c=>c.filter(g=>g.name==='H'&&g.qubit===0).length>=2},
{id:'bell',title:'Create entanglement',difficulty:'Medium',xp:100,goal:'Build a Bell state with correlated 00 and 11 outcomes.',hint:'Start with H(q0), then connect q0 to q1 using CNOT.',validate:c=>c.some(g=>g.name==='H'&&g.qubit===0)&&c.some(g=>g.name==='CNOT'&&g.qubit===0&&g.target===1)},
{id:'grover',title:'Amplify a target',difficulty:'Hard',xp:150,goal:'Use a two-qubit circuit containing a diffusion-style sequence to explore amplitude amplification.',hint:'Start with H on both qubits; experiment with X and H around the target.',validate:c=>c.filter(g=>g.name==='H').length>=2&&c.some(g=>g.name==='X')}
];
