export const GATES={I:[[1,0],[0,1]],X:[[0,1],[1,0]],Y:[[0,'-i'],['i',0]],Z:[[1,0],[0,-1]],H:[[1/Math.sqrt(2),1/Math.sqrt(2)],[1/Math.sqrt(2),-1/Math.sqrt(2)]]};
const cadd=(a,b)=>({re:a.re+b.re,im:a.im+b.im});const cmul=(a,b)=>({re:a.re*b.re-a.im*b.im,im:a.re*b.im+a.im*b.re});const mag2=a=>a.re*a.re+a.im*a.im;
function apply1(s,n,q,m){const out=s.map(x=>({...x}));for(let i=0;i<s.length;i++){if(((i>>q)&1)===0){const j=i|(1<<q);const a=s[i],b=s[j];const mm=m.map(r=>r.map(v=>typeof v==='string'?(v==='i'?{re:0,im:1}:{re:0,im:-1}):{re:v,im:0}));out[i]=cadd(cmul(mm[0][0],a),cmul(mm[0][1],b));out[j]=cadd(cmul(mm[1][0],a),cmul(mm[1][1],b));}}return out}
function applyCNOT(s,control,target){const out=s.map(x=>({...x}));for(let i=0;i<s.length;i++)if(((i>>control)&1)===1){const j=i^(1<<target);if(i<j){out[i]=s[j];out[j]=s[i]}}return out}
export function simulate(n,circuit,shots=1000){let s=Array.from({length:2**n},()=>({re:0,im:0}));s[0]={re:1,im:0};for(const g of [...circuit].sort((a,b)=>(a.col??0)-(b.col??0))){if(g.name==='CNOT')s=applyCNOT(s,g.qubit,g.target??(g.qubit===0?1:0));else if(g.name==='SWAP'){s=applyCNOT(s,g.qubit,g.target??1);s=applyCNOT(s,g.target??1,g.qubit);s=applyCNOT(s,g.qubit,g.target??1)}else if(GATES[g.name])s=apply1(s,n,g.qubit,GATES[g.name]);}
const probs=s.map(mag2);const counts=Array.from({length:2**n},()=>0);for(let k=0;k<shots;k++){let r=Math.random(),acc=0,idx=probs.length-1;for(let i=0;i<probs.length;i++){acc+=probs[i];if(r<=acc){idx=i;break}}counts[idx]++}return {statevector:s,probabilities:probs,counts:counts.map((count,i)=>({basis:i.toString(2).padStart(n,'0'),count,probability:count/shots}))}}
export function blochFromState(s){const a=s[0]||{re:1,im:0},b=s[1]||{re:0,im:0};const x=2*(a.re*b.re+a.im*b.im),y=2*(a.re*b.im-a.im*b.re),z=mag2(a)-mag2(b);return {x,y,z}}
export function circuitText(c){return c.map(g=>`${g.name}(q${g.qubit}${g.target!==undefined?`→q${g.target}`:''})`).join(' → ')||'empty circuit'}
export function parseCode(code){const out=[];let col=0;for(const raw of code.split(/\n|;/)){const line=raw.trim().toLowerCase();let m=line.match(/qc\.(h|x|y|z)\((\d+)\)/);if(m){out.push({id:crypto.randomUUID(),name:m[1].toUpperCase(),qubit:+m[2],col:col++});continue}m=line.match(/qc\.(cx|cnot)\((\d+)\s*,\s*(\d+)\)/);if(m){out.push({id:crypto.randomUUID(),name:'CNOT',qubit:+m[2],target:+m[3],col:col++});continue}m=line.match(/qc\.measure(?:_all)?\(\)/);if(m){out.push({id:crypto.randomUUID(),name:'M',qubit:0,col:col++})}}return out}
